name: supabase

on:
  schedule:
    - cron: '0 12 */6 * *'
  workflow_dispatch:

jobs:
  ping_supabase:
    runs-on: ubuntu-latest

    steps:
      - name: pingsupa
        run: curl -s https://backend-turifa.vercel.app/api/keepalive